//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentBroker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgentBroker()
        {
            this.AgentBroker1 = new HashSet<AgentBroker>();
            this.ContractAgentContracts = new HashSet<ContractAgentContract>();
        }
    
        public int Id { get; set; }
        public bool IsAgentOrBroker { get; set; }
        public int PersonId { get; set; }
        public string ContractNo { get; set; }
        public string InternalContractNo { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsAnnulated { get; set; }
        public Nullable<System.DateTime> AnnulatedDate { get; set; }
        public string AnnulatedComment { get; set; }
        public bool IsDelete { get; set; }
        public bool IsHidden { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> LastModifiedUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ParentAgentBrokerLogId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentBroker> AgentBroker1 { get; set; }
        public virtual AgentBroker AgentBroker2 { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractAgentContract> ContractAgentContracts { get; set; }
    }
}
