//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractAgentContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractAgentContract()
        {
            this.PolicyPaymentCoverAgentContracts = new HashSet<PolicyPaymentCoverAgentContract>();
        }
    
        public int Id { get; set; }
        public int ContractId { get; set; }
        public int AgentBrokerContractId { get; set; }
        public bool IsDelete { get; set; }
        public bool IsHidden { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> LastModifiedUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public int AgentId { get; set; }
        public Nullable<int> CommissionTypeId { get; set; }
        public Nullable<int> TaxTypeId { get; set; }
        public int ProductId { get; set; }
        public decimal CommissionPercent { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual AgentBroker AgentBroker { get; set; }
        public virtual Person Person { get; set; }
        public virtual SubProduct SubProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyPaymentCoverAgentContract> PolicyPaymentCoverAgentContracts { get; set; }
    }
}
