//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyReinsuranceShare
    {
        public int Id { get; set; }
        public int PolicyReinsuranceId { get; set; }
        public int ShareHolderId { get; set; }
        public decimal Percent { get; set; }
        public decimal Risk { get; set; }
        public decimal Premium { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreateUserid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> LastModifiedUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PolicyReinsurance PolicyReinsurance { get; set; }
    }
}
