//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transfer()
        {
            this.Transfer1 = new HashSet<Transfer>();
            this.Transfer11 = new HashSet<Transfer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string DocNumber { get; set; }
        public string Payer { get; set; }
        public Nullable<int> IncomeChanneld { get; set; }
        public Nullable<int> BankId { get; set; }
        public string Account { get; set; }
        public Nullable<decimal> IncomeAmount { get; set; }
        public Nullable<decimal> ExtendAmount { get; set; }
        public Nullable<decimal> CashBackAmount { get; set; }
        public Nullable<decimal> DistributedAmount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int CurrencyId { get; set; }
        public string TaxCode { get; set; }
        public bool IsUsed { get; set; }
        public bool IsDistributed { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<decimal> RateEur { get; set; }
        public Nullable<decimal> RateUsd { get; set; }
        public Nullable<int> TransferStatusId { get; set; }
        public Nullable<int> IncomeTypeId { get; set; }
        public Nullable<int> ParentTransferId { get; set; }
        public Nullable<int> VirtualTransferId { get; set; }
        public bool IsVirtuel { get; set; }
        public bool IsIncomingOrderDistr { get; set; }
        public bool IsDelete { get; set; }
        public bool IsHidden { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedUserId { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> IncomeDate { get; set; }
        public Nullable<int> IncomingOrderId { get; set; }
        public Nullable<System.DateTime> To1CSynchronizeDate { get; set; }
        public Nullable<bool> NeedsReSynchronizeTo1C { get; set; }
        public string Comment { get; set; }
    
        public virtual IncomeType IncomeType { get; set; }
        public virtual IncomeType IncomeType1 { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfer1 { get; set; }
        public virtual Transfer Transfer2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfer11 { get; set; }
        public virtual Transfer Transfer3 { get; set; }
        public virtual IncomingOrderTable IncomingOrderTable { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
